version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: glif-test_postgres:custom # Add an image tag
    container_name: postgres-db
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - postgres-network

volumes:
  postgres_data:

networks:
  postgres-network: